### ISSUE TITLE
Requires webpack to resolve CSS and 'stackframe'

### ISSUE THREAD

**Issue by ryngonzalez** [KeywordBrain/redbox-react#17]
I'm using redbox-react in a non-webpack project (specifically using Browserify) and I'm receiving some module resolution errors for both the 'stackframe' module and the bundled css: 

<img width="1419" alt="screenshot 2015-09-13 21 34 37" src="https://cloud.githubusercontent.com/assets/635300/9842188/9528261c-5a5f-11e5-9f99-e7e0db4325b6.png">

Anything I'm missing here to make this work correctly?

**Comment by davidpfahler** [comment]
@ryngonzalez Please check out the latest version. I think we just fixed that. If not, please ping me here.

**Comment by AgentME** [comment]
I'm still seeing the "Error: Cannot find module 'stackframe' from..." error with version 1.0.5 when trying to use this with Browserify.

Here's a quick example:

```
[chris /tmp/a]$ npm i react redbox-react
redbox-react@1.0.5 node_modules/redbox-react
└── error-stack-parser@1.2.2 (stackframe@0.3.1)

react@0.13.3 node_modules/react
└── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
[chris /tmp/a]$ echo "require('redbox-react')" > test.js
[chris /tmp/a]$ browserify test.js 
Error: Cannot find module 'stackframe' from '/private/tmp/a/node_modules/redbox-react/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```
